### PR TITLE
GP-11278 - added support for GP_MAX_CONCURRENT_PROJECTS_PER_ORG

### PR DESCRIPTION
**Pull request by Alchemys**
GP-11278 - added support for GP_MAX_CONCURRENT_PROJECTS_PER_ORG environment variable for ticket and pr processing

### CODE REVIEW

**Review by dcumberland — CHANGES_REQUESTED** [review]
Unfortunately, we've had some trouble with making structural changes to a helm chart in-version.  Instead, we've had to roll a new version to ensure the configs get deployed correctly.

The change you're making looks fine, but I strongly recommend making the change via setting up v3.0.6

**Comment by Alchemys** [comment]
> Unfortunately, we've had some trouble with making structural changes to a helm chart in-version. Instead, we've had to roll a new version to ensure the configs get deployed correctly.
> 
> The change you're making looks fine, but I strongly recommend making the change via setting up v3.0.6

Ok, I'll copy everything to a v3.0.6 folder with my changes and revert the changes I made inside the v3.0.5 folder

**Review by nate-taylor1 — APPROVED** [review]
LGTM

**Review by dcumberland — APPROVED** [review]
LGTM

**Pull request merged**
