### PR TITLE
Dp 846/dp consumer app

### PR DESCRIPTION
**Pull request by nate-taylor1**
Adding consumer worker type for data pipeline.

### CODE REVIEW

**Review by jawadshaikps — APPROVED** [review]
+1

**Review by bajolly — COMMENTED** [review]
Do we want to use a version in directory name.  That doesn't seem correct.

**Comment by ghost** [comment]
> Do we want to use a version in directory name. That doesn't seem correct.

@bajolly I believe the way we currently have DP deployed in Rancher needs this type of format.  Russ is working on moving over to the newer version of helm charts.

**Review by Alchemys — APPROVED** [review]
LGTM
(Can't _wait_ for the new format since this is super hard to review without a diff)

**Pull request merged**
